apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
      version: blue
  template:
    metadata:
      labels:
        app: pythonapp
        version: blue
    spec:
      containers:
      - name: pythonapp
        image: anirudh3369/myapp:latest
        ports:
        - containerPort: 5000  # Flask default port
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
