apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  selector:
    app: pythonapp
    version: blue  # initially points to blue
  ports:
  - protocol: TCP
    port: 80       # external port
    targetPort: 5000  # Python app port
  type: LoadBalancer
